Attribute VB_Name = "Dil_Seçeneði"
Public Function Turkce()
Form1.Command1.Caption = "Giriþ"
Form1.Command2.Caption = "Çýkýþ"
Form1.Label1.Caption = "Kullanýcý Adý :"
End Function
Public Function English()
'Cleaner
Form1.Check4.Caption = "Internet History"
Form1.Check5.Caption = "Saved Passwords"
Form1.Check6.Caption = "Download History"
Form1.Check7.Caption = "Internet History"
Form1.Check8.Caption = "Saved Passwords"
Form1.Check9.Caption = "Download History"
Form1.Check10.Caption = "Internet History"
Form1.Check11.Caption = "Saved Passwords"
Form1.Check12.Caption = "Download History"
Form1.Tab1.Item(0).Caption = "Windows"
Form1.Tab1.Item(1).Caption = "Browsers"
Form1.CheckBox2.Caption = "Empty Trash"
Form1.CheckBox3.Caption = "Start Menu Shortcuts"
Form1.CheckBox4.Caption = "Desktop Shortcuts"
Form1.CheckBox5.Caption = "Last Open Files"
Form1.CheckBox6.Caption = "Unnecessary Temp Files"
Form1.Command5.Caption = "Start Cleaning"
Form1.Command6.Caption = "Cancel"

'Ayarlar
'Form1.Label3.Caption = "Language :"
'Form1.CheckBox17.Caption = "Let The Computer Program When Opened"
'Form1.CheckBox19.Caption = "Clean finished then the Close Program"
'Form1.CheckBox21.Caption = "Clean finished Then the Warning / Alarm Player"
'Form1.CheckBox22.Caption = "Tray Shrink System"
'Form1.GroupBox2.Caption = "[ Transparency ]"
Form1.TabControl1.Item(0).Caption = "Options"
Form1.TabControl1.Item(1).Caption = "About"

'Araçlar
Form1.CheckBox7.Caption = "1.Windows XP Fast Shutdown"
Form1.CheckBox10.Caption = "2. More CPU Power"
Form1.CheckBox9.Caption = "3. Speed On Windows XP"
Form1.CheckBox15.Caption = "4. Acceleration of Windows More"
Form1.CheckBox14.Caption = "5. Memory Performance Enhancement"
Form1.CheckBox12.Caption = "6. Start Menu Acceleration"
Form1.CheckBox13.Caption = "7. Reduction of Visual Effects"
Form1.CheckBox20.Caption = "8. Bip'lerini Removal System"
Form1.CheckBox11.Caption = "9. Internet Speed Increase 20%"
Form1.CheckBox8.Caption = "10. Speech Balloons"
Form1.CheckBox16.Caption = "11. Remove XP Components"
Form1.Tab2.Item(0).Caption = "Ýnception"
Form1.Tab2.Item(1).Caption = "System Optimization / Acceleration"
Form1.GroupBox1.Caption = "[PC Features]"
Form1.PushButton4.Caption = "Apply to improve"
Form1.PushButton5.Caption = "Cancel Improvement"
Form1.PushButton1.Caption = "Add Entry"
'Form1.PushButton3.Caption = "Refresh List"
Form1.PushButton2.Caption = "Delete the selected entry"
End Function

